#!/bin/bash
set -e

apt-get update -y
apt-get install -y ca-certificates curl git

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

tee /etc/apt/sources.list.d/docker.sources >/dev/null <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl enable --now docker

usermod -aG docker ubuntu

mkdir -p /opt/deutschmeister
cd /opt/deutschmeister

git clone https://github.com/YESHUBGIT/DeutschMeisterApp.git .

cat > .env <<'EOF'
NEXTAUTH_URL=https://thecloudtitan.de
NEXTAUTH_SECRET=nextauthsecret
NEXTAUTH_TRUST_HOST=true

COGNITO_CLIENT_ID="7t9po5p2tkmqqd9sl02lbeb8t"
COGNITO_CLIENT_SECRET="cdtmfs89qgic0td63gamdh6poepr8e36j8vvd0b9o89covnhv55"
COGNITO_ISSUER="https://cognito-idp.us-east-1.amazonaws.com/us-east-1_NLWDaRRCx"

POSTGRES_PASSWORD=pguserpassword
EOF

docker pull yeshdock/deutschmeister:latest
docker compose up -d
